name: Matrix Demo
on: 
  push:
    branches:
      - master
jobs:
  build:
    #continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        oper-sys: [ubuntu-latest, windows-latest]
        include: 
          - node-version: 18
          - oper-sys: ubuntu-latest
        exclude:
          - node-version: 12
          - oper-sys: windows-latest
          
    runs-on: ${{ matrix.oper-sys }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node Js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build